name: Accessibility Markdown Linter

on:
  push:
    branches:
      - main

jobs:
  check_formatting:
    runs-on: ubuntu-latest
    steps:
      - name: markdownlint-cli2-action
        uses: DavidAnson/markdownlint-cli2-action@v10.0.1
